# Generated by Django 4.1 on 2022-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='asistencia',
        ),
    ]
