# Generated by Django 4.1 on 2022-09-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasio', '0002_abonos_delete_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='contaco',
            new_name='contacto',
        ),
    ]
